version: '3'
services:
  database-mongo:
    container_name: tech_challenge_database_mongo
    image: mongo:latest
    platform: linux/amd64
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=pos-tech-fiap
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tech_challenge_fiap

  api:
    depends_on:
      - database-mongo
    container_name: tech_challenge_api
    image: postechfiap01/order-management:v1
    platform: linux/amd64
    ports:
      - '8080:8080'
    environment:
      - APP_ENV=prod
      - DB_STORAGE=mongo
      - DB_HOST=database-mongo
      - DB_PORT=27017
      - DB_USER=docker
      - DB_PASSWORD=123
      - DB_NAME=pos-tech-fiap
      - DB_URI=mongodb://database-mongo:27017/pos-tech-fiap
      - TOKEN_MERCADO_PAGO=TEST-2373946154784631-101516-50ff7f4dcdff3aec43372568c77990e3-175794680
    restart: always
    networks:
      - tech_challenge_fiap

volumes:
  mongo_data: {}

networks:
  tech_challenge_fiap:
    driver: bridge
