version: '3'
services:
  database-pg:
    container_name: tech_challenge_database_pg
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=tech_challenge_fiap
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/db/migrations/postgres:/docker-entrypoint-initdb.d/
    networks:
      - tech_challenge_fiap
  
  database-mongo:
    container_name: tech_challenge_database_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=tech_challenge_fiap
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - tech_challenge_fiap
      
  api:
    depends_on:
      - database-mongo
    container_name: tech_challenge_api
    image: caiomartinspereira/order-management:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=prod
      - DB_STORAGE=mongo
      - DB_HOST=database-mongo
      - DB_PORT=27017
      - DB_USER=docker
      - DB_PASSWORD=123
      - DB_NAME=tech_challenge_fiap
    restart: always
    networks:
      - tech_challenge_fiap
  
volumes:
  postgres_data: {}
  mongo_data: {}

networks:
  tech_challenge_fiap:
    driver: bridge
