apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order-management
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-management
    spec:
      containers:
      - name: order-management
        image: caiomartinspereira/order-management:v2.0.9
        envFrom:
          - configMapRef:
              name: order-management
          - secretRef:
              name: order-management
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
