# Por boa prática e principalmente por segurança não devemos subir arquivos de secrets para o repositório remoto por conter dados sensíveis.
# Adicionei aqui o manifesto da secret para demonstrar que usamos essa abordagem para rodar nossa aplicação no cluster kubernetes.

apiVersion: v1
kind: Secret
metadata:
  name: order-management
type: Opaque
data:
  DB_URI: <secret-base64-here>
